Added debug info option
foss-for-synopsys-dwc-arc-processors/arc-gnu-toolchain pull request #20
Opened 2023-04-24 09:31 UTC by luismgsilva

Added option to enable (--enable-debug) or disable (--disable-debug) the debug information in the building process in order to reduce the size of the toolchain distribution.
This option is enabled by default.

This is a request from https://github.com/foss-for-synopsys-dwc-arc-processors/arc-gnu-toolchain/issues/11 .

2023-04-24 12:14 UTC, shahab-vahedi requested changes

2023-04-24 12:14 UTC, shahab-vahedi commented on Makefile.in
> +		CFLAGS="$(CFLAGS_FOR_TARGET) @debug_flag@ -O2 $($@_CFLAGS)" \
Put `-O2` before the `@debug_flag@`.

2023-04-24 12:14 UTC, shahab-vahedi commented on Makefile.in
> +		CXXFLAGS="$(CXXFLAGS_FOR_TARGET) @debug_flag@ -O2 $($@_CFLAGS)" \
Put `-O2` before the `@debug_flag@`.

2023-05-17 10:24 UTC, luismgsilva commented
## Results

### Baremetal Toolchain
| Directories 		| Default 	| Debug (--enable-debug-info) 	|  Release (--disable-debug-info) |
|-------------		|:-------------:|:-------------:|:-------------:|
|       ./include      	|   20K      	|      20K      	|         20K 	|
|      ./lib       	|      15M   	|      38M      	|        11M  	|
|      ./share       	|      17M   	|      17M      	|          17M	|
|      ./arc64-elf      |      23M   	|      132M      	|      23M    	|
|      ./bin       	|     538M    	|        356M    	|       91M   	|
|      ./libexec       	|      743M   	|      452M      	|      123M    	|
|      ./       	|        1.4G 	|       992M     	|       263M   	|


### Linux Toolchain
| Directories 		| Default 	| Debug (--enable-debug-info) 	|  Release (--disable-debug-info) |
|-------------		|:-------------:|:-------------:|:-------------:|
|       ./include      	|      20K   	|       20K     	|       20K   	|
|      ./lib       	|      16M	|    44M        	|       11M   	|
|      ./share       	|      18M	|      18M      	|        18M  	|
|      ./arc64-linux-gnu |      76M  	|     255M       	|       45M   	|
|      ./bin       	|     472M  	|      316M      	|        77M  	|
|      ./libexec       	|      	987M	|     598M       	|        163M  	|
|      ./sysroot       	|      1.2G	|     1.3G       	|       65M   	|
|      ./       	|    	2.7G	|     2.5G       	|       377M   	|

## TLDR

The updated approach for building the toolchain has resulted in the emergence of new failing tests for both `Baremetal` and `Linux` distributions. These failures are associated with the debugging aspects of the compilation process.

In the case of `Baremetal`, the new failing tests exhibit behavior that relies on Linux tools such as `mkdir`, `pathconf`, and `getcwd`. This issue could be potencially be related to a problem with newlib.

For `Linux`, the new failing test is connected to the build process of glibc, where the use of the `-Og` flag instead of `-O2` appears to be the cause.


## Configuration

### Build for ARC64 Baremetal
```sh
# /scratch/luiss/builds/debug/build-arc64-baremetal
$ ../arc-gnu-toolchain/configure 									\
		--prefix=/scratch/luiss/builds/debug/build-arc64-baremetal/../install-arc64-baremetal 	\
		--target=arc64 										\
		--disable-werror
$ make -j32
```

### Build for ARC64 Linux
```sh
# /scratch/luiss/builds/debug/build-arc64-linux

$ ../arc-gnu-toolchain/configure					 				\
		--prefix=/scratch/luiss/builds/debug/build-arc64-linux/../install-arc64-linux 		\
		--target=arc64 										\
		--enable-linux
$ make -j32
```


## Smoke Tests Default Toolchain Distribution

This report utilizes the smoke tests from the `arc-gnu-toolchain` repository. To execute these tests, the command `make report -j<NPROC>` should be used. This command will clone and compile the most recent version of QEMU, along with compiling the tests themselves.

### Results ARC64 Baremetal
```sh
$ make report -j32
/scratch/luiss/issues/arc-gnu-toolchain/11/default/build-arc64-baremetal/../arc-gnu-toolchain/scripts/testsuite-filter newlib \
	/scratch/luiss/issues/arc-gnu-toolchain/11/default/build-arc64-baremetal/../arc-gnu-toolchain/test/allowlist/gcc/hs6x/gcc.json \
	`find build-gcc-newlib-stage2 -name *.sum |paste -sd "," -`
/scratch/luiss/issues/arc-gnu-toolchain/11/default/build-arc64-baremetal/../arc-gnu-toolchain/scripts/testsuite-filter newlib \
	/scratch/luiss/issues/arc-gnu-toolchain/11/default/build-arc64-baremetal/../arc-gnu-toolchain/test/allowlist/binutils/binutils.json \
	`find build-binutils-newlib -name *.sum |paste -sd "," -`
=== gas ld binutils: Unexpected fails for arc-sim ===

=== ERROR ===
    arc64-elf-cc does not exist
    arc64-elf-cc does not exist
    arc64-elf-cc does not exist
=== FAIL ===
    simple objcopy of executable


# Tests | # Detected Errors
--------+------------------
   1169 |       4

=== g++ gcc: Unexpected fails for arc-sim ===

=== XPASS ===
=== FAIL ===


# Tests | # Detected Errors
--------+------------------
 328584 |       0

```

### Results ARC64 Linux

```sh
$ make report -j32
/scratch/luiss/issues/arc-gnu-toolchain/11/default/build-arc64-linux/../arc-gnu-toolchain/scripts/testsuite-filter linux \
	/scratch/luiss/issues/arc-gnu-toolchain/11/default/build-arc64-linux/../arc-gnu-toolchain/test/allowlist/gcc/hs6x/gcc.json \
	`find build-gcc-linux-stage2 -name *.sum |paste -sd "," -`
/scratch/luiss/issues/arc-gnu-toolchain/11/default/build-arc64-linux/../arc-gnu-toolchain/scripts/testsuite-filter linux \
	/scratch/luiss/issues/arc-gnu-toolchain/11/default/build-arc64-linux/../arc-gnu-toolchain/test/allowlist/binutils/binutils.json \
	`find build-binutils-linux -name *.sum |paste -sd "," -`
=== gas ld binutils: Unexpected fails for arc-sim ===

=== FAIL ===
    ld-elf/pr19539
    DT_TEXTREL in shared lib
    DT_TEXTREL map file warning
    pr20995
    pr20995-2
    Build pr23162a
    Build pr23162b
    Build pr22263-1
    plugin claimfile lost symbol
    plugin claimfile replace symbol
    plugin claimfile resolve symbol
    load plugin with source
    plugin claimfile lost symbol with source
    plugin claimfile replace symbol with source
    plugin claimfile resolve symbol with source
    plugin claimfile replace file with source
    plugin set symbol visibility with source
    plugin ignore lib with source
    plugin claimfile replace lib with source
    plugin 2 with source lib
    load plugin 2 with source
    load plugin 2 with source and -r
    plugin 3 with source lib
    load plugin 3 with source
    load plugin 3 with source and -r
    PR ld/20070
    Could not create a shared library containing an unique symbol with reference


# Tests | # Detected Errors
--------+------------------
   2013 |      27

=== gcc g++ gfortran: Unexpected fails for arc-sim ===

=== FAIL ===
    gcc.dg/di-sync-multithread.c execution test
    gcc.target/arc64/interrupt-5.c scan-assembler popl_s\\s+r30\n
    gcc.target/arc64/interrupt-5.c scan-assembler pushl_s\\s+r30\n
    c-c++-common/goacc/kernels-decompose-pr100400-1-2.c  -std=c++14 (test for excess errors)
    c-c++-common/goacc/kernels-decompose-pr100400-1-2.c  -std=c++17 (test for excess errors)
    c-c++-common/goacc/kernels-decompose-pr100400-1-2.c  -std=c++20 (test for excess errors)
    c-c++-common/goacc/kernels-decompose-pr100400-1-2.c  -std=c++98 (test for excess errors)
    gfortran.dg/bind_c_array_params_2.f90   -O   scan-assembler-times [ \t][$,_0-9]*myBindC 1
    gfortran.dg/elemental_subroutine_3.f90   -O3 -fomit-frame-pointer -funroll-loops -fpeel-loops -ftracer -finline-functions  (test for excess errors)
    gfortran.dg/matmul_15.f90   -O  execution test
    gfortran.dg/pr95690.f90   -O   (test for errors, line 6)
    gfortran.dg/pr95690.f90   -O  (test for excess errors)
    gfortran.dg/pr98076.f90   -O0  execution test
    gfortran.dg/pr98076.f90   -O1  execution test
    gfortran.dg/pr98076.f90   -O2  execution test
    gfortran.dg/pr98076.f90   -O3 -fomit-frame-pointer -funroll-loops -fpeel-loops -ftracer -finline-functions  execution test
    gfortran.dg/pr98076.f90   -O3 -g  execution test
    gfortran.dg/pr98076.f90   -Os  execution test
    gfortran.dg/ieee/ieee_1.F90   -O0  execution test
    gfortran.dg/ieee/ieee_1.F90   -O1  execution test
    gfortran.dg/ieee/ieee_1.F90   -O2  execution test
    gfortran.dg/ieee/ieee_1.F90   -O3 -fomit-frame-pointer -funroll-loops -fpeel-loops -ftracer -finline-functions  execution test
    gfortran.dg/ieee/ieee_1.F90   -O3 -g  execution test
    gfortran.dg/ieee/ieee_1.F90   -Os  execution test
    gfortran.dg/ieee/ieee_2.f90   -O0  execution test
    gfortran.dg/ieee/ieee_2.f90   -O1  execution test
    gfortran.dg/ieee/ieee_2.f90   -O2  execution test
    gfortran.dg/ieee/ieee_2.f90   -O3 -fomit-frame-pointer -funroll-loops -fpeel-loops -ftracer -finline-functions  execution test
    gfortran.dg/ieee/ieee_2.f90   -O3 -g  execution test
    gfortran.dg/ieee/ieee_2.f90   -Os  execution tes [...]

2023-06-22 15:33 UTC, merged